微信 :
配置 :
 #Configure a text template ID
 单个模板ID : 07664e7f9d8cd09d57ef3827026a40fa
模板 :
 #Good Morning Template
 模板 :
 #Template ID
 模板Id : JSoULM8uEgY9wM4A3BxEnxBP7ci-FxREWIEVhw9Sily公司
 #Whether all followed users are sent, True is Yes. When the value is true, SendOpenId is the WeChat user excluding the sending object. When the value is false, it means no, SendOpenId is the WeChat user of the sending object
 全部发送 :真的
过滤器 :
参数 :
 #This is the default setting. If a user does not set parameters, press this parameter
违约 :
 #Good morning speech
标题 : Good morning Yaya
 #Your meeting time
 会议日期 : &#39;2019-10-25&#39;
城市 : Xiangtan
 #Location of residence, download and query of Gaode map api https://lbs.amap.com/api/webservice/download
 城市代码 : four hundred and thirty thousand and three hundred
 #&#39;Fill in your WeChat user ID that needs specific configuration&#39; is overwritten as WeChat user ID, which can be compared with the correctly filled configuration example, and multiple users can continue to add according to the format
 #Color text template
 表情模板 :FQDR1-9QccN6OZWCPwYo69paNTli2YBlOHXmt_6-dSA
 模板Id : Fill in the template ID
 全部发送 :真的
过滤器 :
参数 :
违约 :
标题 : one
 #Sender&#39;s personal information
个人的 :
信息 :
星座 : Gemini

