server:
  servlet:
    context-path: /wechat/demo
  port: 8081

wechat:
  config:
    #微信appId
    appId: wx0a3d7874237a5c7f
    #微信appSecret
    appSecret: 07664e7f9d8cd09d57ef3827026a40fa
    template:
      #早安模板
      morningTemplate:
        #模板ID
        templateId: JSoULM8uEgY9wM4A3BxEnxBP7ci-FxREWIEVhw9SilY
        #是否关注的用户全发送，ture为是，当值为ture时，sendOpenId 为排除发送对象的微信用户，当值为false为否，sendOpenId为发送对象的微信用户
        allSend: true
        filterOpenIds:
#          - 微信用户号
#          - oq-DD6qRIGGmdE4iO4BQN81y4fWI
        parameter:
          #这是默认的设置，如果有用户没设置参数，就按此参数
          default:
            #早安话语
            title: 早上好呀呀鸭
            #你们的相遇时间
            meetDate: '1996-06-18'
            city: 广州
            #居住地点，高德地图api下载查询 https://lbs.amap.com/api/webservice/download
            cityCode: 440100
          #用户openID，多用户可以按照格式继续添加下去
          oq-DD6qRIGGmdE4iO4BQN81y4fWI:
            title: 早上好呀呀鸭
            meetDate: '2021-08-11'
            city: 肇庆
            cityCode: 440600
       
lbs:
  key: 5d6ad80af571fb3dfbd10c467e9c78d9
